var a = 1042;
var b = 'apples and oranges';
var c = 'pineapples';
var d = [true, true, false];
var e = { type: 'ficus' };
var f = [1, false];
var g = [3];
var h = null;
console.log(typeof a);
console.log(typeof b);
console.log(typeof c);
console.log(typeof d);
console.log(typeof e);
console.log(typeof f);
console.log(typeof g);
console.log(typeof h);
